# Generated by Django 5.1 on 2024-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='адрес'),
        ),
    ]
