# Generated by Django 5.1 on 2024-08-21 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cake',
            old_name='Berrie',
            new_name='berrie',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='Decor',
            new_name='decor',
        ),
        migrations.RenameField(
            model_name='cake',
            old_name='Topping',
            new_name='topping',
        ),
        migrations.AddField(
            model_name='cake',
            name='inscription',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 10, 21, 5, 134450), verbose_name='Дата'),
        ),
    ]
