# Generated by Django 5.1 on 2024-08-21 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0003_rename_berrie_cake_berrie_rename_decor_cake_decor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(upload_to='images/cakes', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 22, 10, 44, 32, 868159), verbose_name='Дата'),
        ),
    ]
