# Generated by Django 5.1 on 2024-08-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0004_alter_cake_image_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='shape',
            field=models.CharField(choices=[('ROUND', 'круг'), ('SQUARE', 'квадрат'), ('RECTANGLE', 'прямоугольник')], max_length=25, verbose_name='Форма (круг, квадрат, прямоугольник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
