# Generated by Django 5.1 on 2024-08-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0008_order_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Berrie',
            new_name='Berry',
        ),
    ]
