# Generated by Django 5.1 on 2024-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0010_layer_shape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='shape',
        ),
        migrations.AddField(
            model_name='layer',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество уровней (1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='title',
            field=models.CharField(choices=[('ROUND', 'круг'), ('SQUARE', 'квадрат'), ('RECTANGLE', 'прямоугольник')], max_length=25, verbose_name='Форма (круг, квадрат, прямоугольник'),
        ),
    ]
