# Generated by Django 5.1 on 2024-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0011_remove_cake_shape_layer_number_alter_shape_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='number',
            field=models.PositiveIntegerField(verbose_name=' Количество уровней (1, 2, 3'),
        ),
    ]
