# Generated by Django 5.1 on 2024-08-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0012_alter_layer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='levels_number',
        ),
        migrations.AddField(
            model_name='cake',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='BakeCake.shape', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='number',
            field=models.PositiveIntegerField(verbose_name=' Количество уровней (1, 2, 3)'),
        ),
    ]
