# Generated by Django 5.1 on 2024-08-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0013_remove_cake_levels_number_cake_shape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='levels_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='BakeCake.layer', verbose_name='Количество уровней'),
        ),
    ]
