# Generated by Django 5.1 on 2024-08-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0014_cake_levels_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='number',
            field=models.PositiveIntegerField(verbose_name=' Количество уровней'),
        ),
        migrations.AlterField(
            model_name='shape',
            name='title',
            field=models.CharField(choices=[('ROUND', 'Круг'), ('SQUARE', 'Квадрат'), ('RECTANGLE', 'Прямоугольник')], max_length=25, verbose_name='Форма'),
        ),
    ]
