# Generated by Django 5.1 on 2024-08-22 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0017_order_delivery_comment_alter_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='berry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.berry', verbose_name='Ягода'),
        ),
        migrations.AddField(
            model_name='order',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.decor', verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='order',
            name='inscription',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Надпись'),
        ),
        migrations.AddField(
            model_name='order',
            name='levels_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.layer', verbose_name='Количество уровней'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.shape', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='BakeCake.topping', verbose_name='Топпинг'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(default='images/cakes/Cake.png', upload_to='images/cakes', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='BakeCake.cake', verbose_name='Торт'),
        ),
    ]
