# Generated by Django 5.1 on 2024-08-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0018_order_berry_order_decor_order_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='is_public',
        ),
    ]
